### ISSUE TITLE
getting error in creating production build: npm run start:prod

### ISSUE THREAD

**Issue by prashantidealittechno** [kentloog/nestjs-sequelize-typescript#1]
> nest-sequelize-typescript@0.0.1 start:dev /home/ideal21/Documents/NestJs/nestjs-sequelize-typescript
> nodemon

[nodemon] 1.18.11
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /home/ideal21/Documents/NestJs/nestjs-sequelize-typescript/src/**/*
[nodemon] starting `ts-node -r tsconfig-paths/register src/main.ts`
[Nest] 12469   - 05/15/2019, 9:43 AM   [NestFactory] Starting Nest application...
[Nest] 12469   - 05/15/2019, 9:43 AM   [InstanceLoader] AppModule dependencies initialized +26ms
[Nest] 12469   - 05/15/2019, 9:43 AM   [InstanceLoader] SharedModule dependencies initialized +0ms
[Nest] 12469   - 05/15/2019, 9:43 AM   [InstanceLoader] PostsModule dependencies initialized +339ms
[Nest] 12469   - 05/15/2019, 9:43 AM   [InstanceLoader] UsersModule dependencies initialized +2ms
(node:12469) [SEQUELIZE0002] DeprecationWarning: The logging-option should be either a function or false. Default: console.log
Executing (default): CREATE TABLE IF NOT EXISTS `user` (`id` CHAR(36) BINARY , `email` VARCHAR(255) UNIQUE, `password` VARCHAR(255), `first_name` VARCHAR(255), `last_name` VARCHAR(255), `gender` ENUM('female', 'male'), `birthday` DATE, `created_at` DATETIME, `updated_at` DATETIME, `deleted_at` DATETIME, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `user` FROM `nest`
Executing (default): CREATE TABLE IF NOT EXISTS `post` (`id` BIGINT auto_increment , `user_id` CHAR(36) BINARY, `title` VARCHAR(255), `content` VARCHAR(255), `created_at` DATETIME, `updated_at` DATETIME, `deleted_at` DATETIME, PRIMARY KEY (`id`), FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `post` FROM `nest`
[Nest] 12469   - 05/15/2019, 9:43 AM   [InstanceLoader] DatabaseModule dependencies initialized +175ms
[Nest] 12469   - 05/15/2019, 9:43 AM   [RoutesResolver] UsersController {/users}: +363ms
[Nest] 12469   - 05/15/2019, 9:43 AM   [RouterExplorer] Mapped {/register, POST} route +8ms
[Nest] 12469   - 05/15/2019, 9:43 AM   [RouterExplorer] Mapped {/login, POST} route +2ms
[Nest] 12469   - 05/15/2019, 9:43 AM   [RouterExplorer] Mapped {/, GET} route +2ms
[Nest] 12469   - 05/15/2019, 9:43 AM   [RouterExplorer] Mapped {/me, GET} route +2ms
[Nest] 12469   - 05/15/2019, 9:43 AM   [RouterExplorer] Mapped {/me, PUT} route +2ms
[Nest] 12469   - 05/15/2019, 9:43 AM   [RouterExplorer] Mapped {/me, DELETE} route +1ms
[Nest] 12469   - 05/15/2019, 9:43 AM   [RoutesResolver] PostsController {/posts}: +1ms
[Nest] 12469   - 05/15/2019, 9:43 AM   [RouterExplorer] Mapped {/, GET} route +2ms
[Nest] 12469   - 05/15/2019, 9:43 AM   [RouterExplorer] Mapped {/:id, GET} route +2ms
[Nest] 12469   - 05/15/2019, 9:43 AM   [RouterExplorer] Mapped {/, POST} route +2ms
[Nest] 12469   - 05/15/2019, 9:43 AM   [RouterExplorer] Mapped {/:id, PUT} route +1ms
[Nest] 12469   - 05/15/2019, 9:43 AM   [RouterExplorer] Mapped {/:id, DELETE} route +2ms
[Nest] 12469   - 05/15/2019, 9:43 AM   [NestApplication] Nest application successfully started +5ms
^C
ideal21@ideal21:~/Documents/NestJs/nestjs-sequelize-typescript$ npm run start:prod

> nest-sequelize-typescript@0.0.1 prestart:prod /home/ideal21/Documents/NestJs/nestjs-sequelize-typescript
> rimraf dist && npm run build

> nest-sequelize-typescript@0.0.1 build /home/ideal21/Documents/NestJs/nestjs-sequelize-typescript
> tsc -p tsconfig.build.json

> nest-sequelize-typescript@0.0.1 start:prod /home/ideal21/Documents/NestJs/nestjs-sequelize-typescript
> node dist/main.js

internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '/home/ideal21/Documents/NestJs/nestjs-sequelize-typescript/dist/main.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nest-sequelize-typescript@0.0.1 start:prod: `node dist/main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nest-sequelize-typescript@0.0.1 start:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ideal21/.npm/_logs/2019-05-15T04_13_37_533Z-debug.log

**Comment by kentloog** [comment]
fixed
