### ISSUE TITLE
npm run db:migrate, error in windows

### ISSUE THREAD

**Issue by chenguzhen87** [kentloog/nestjs-sequelize-typescript#5]
![image](https://user-images.githubusercontent.com/28331609/76307397-b91da180-6303-11ea-800b-010b255fbe05.png)

**Comment by dPliakos** [comment]
This problem is not originated from this repo, it's coming from the sequelize/cli 
There is a very old issue there related to that problem, I would try to use git bash (if you are not already using it)

> References https://github.com/sequelize/cli/issues/633
